version: "3"
services:
  django:
    build: .
    container_name: django
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgresDb-data:/var/lib/postgresql/data
  pgAdmin4:
    image: dpage/pgadmin4
    container_name: pgAdmin4
    ports:
      - 82:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - pgdb
    restart: always
    volumes:
      - pgAdmin-data:/var/lib/pgadmin
volumes:
  pgAdmin-data:
    driver: local
  postgresDb-data:
    driver: local
